---
- name: Install Language Packages
  hosts: all
  gather_facts: true

  vars_files:
    - ../../../default.config.yml

  pre_tasks: []

  roles: []

  tasks:
    # NOTE: install Rust via Homebrew can be odd, perhaps use alternatives
    - name: Install Rust packages
      shell: $(brew --prefix rust)/bin/cargo install "{{ item.name }}"
      args:
        executable: bash
      loop: "{{ cargo_packages }}"
      ignore_errors: true
      tags: ["rust"]

    - name: Allow Global Composer plugins
      community.general.composer:
        command: config
        global_command: true
        arguments: allow-plugins.{{ item.name }} true
        composer_home: "{{ composer_cache_directory | expanduser }}"
      loop: "{{ composer_plugins }}"
      ignore_errors: true
      tags: ["php"]

    - name: Install PHP packages
      community.general.composer:
        command: require
        global_command: true
        arguments: "{{ item.name }}"
        composer_home: "{{ composer_cache_directory | expanduser }}"
      loop: "{{ composer_packages }}"
      ignore_errors: true
      tags: ["php"]

    # NOTE: install Go via Homebrew can be odd, perhaps use alternatives
    # https://github.com/suzuki-shunsuke/ansible-go-module alternative
    - name: Install Go packages
      shell: export GOROOT="$(brew --prefix golang)/libexec" && go install "{{ item.name }}"
      args:
        executable: bash
      loop: "{{ go_packages }}"
      ignore_errors: true
      tags: ["go"]

    - name: Install Ruby packages
      community.general.gem:
        name: "{{ item.name }}"
        state: latest
      loop: "{{ gem_packages }}"
      ignore_errors: true
      tags: ["ruby"]

    - name: Install Global NPM packages
      community.general.npm:
        name: "{{ item.name }}"
        global: true
      loop: "{{ npm_packages }}"
      ignore_errors: true
      tags: ["node"]

    # NOTE: install Python package via pipx 
    - name: Install Python packages
      community.general.pipx:
        name: "{{ item.name | default(item) }}"
        state: install
        executable: "{{ item.executable | default('/opt/homebrew/bin/pipx') }}"
      loop: "{{ pip_packages }}"
      ignore_errors: true
      tags: ["python"]

  post_tasks: []
