#!/usr/bin/env bash

# Set stop on error / enable debug
set -euo pipefail
#set -vx

SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPTS_DIR/../../scripts/_common"
HOST_TYPE="macos"

############################################################################
# OPEN ARD ON MACOS HOST
############################################################################

if [[ ! -x "$(command -v jq)" ]]; then
    echo -e "\n${C_ERR}jq is required!${C_RES}"
    exit 1
fi

HOST_INFO=$(terraform output -json hosts)
SSH_HOST=$(echo "$HOST_INFO" | jq -r ".$HOST_TYPE.name")
SSH_USER=$(echo "$HOST_INFO" | jq -r ".$HOST_TYPE.user")

echo -e "\n${C_HIL}Connecting to ARD on ec2-user@$SSH_HOST:${C_RES}"
read -s -r -p "Enter sudo password for ec2-user: " PASS

osascript -e "tell app \"Finder\" to open location \"vnc://$SSH_USER=:$PASS@localhost:5900\""
