#!/usr/bin/env bash

# Set stop on error / enable debug
set -euo pipefail
#set -vx

SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPTS_DIR/../../scripts/_common"
HOST_TYPE=${1:-"linux"}; if [[ "${1:-""}" != "" ]]; then shift; fi

############################################################################
# SEND SSH KEY TO HOST
############################################################################

if [[ ! -x "$(command -v jq)" ]]; then
    echo -e "\n${C_ERR}jq is required!${C_RES}"
    exit 1
fi

if [[ "$HOST_TYPE" == "macos" ]]; then
    SSH_HOME="/Users"
else
    SSH_HOME="/home"
fi
HOST_INFO=$(terraform output -json hosts)
KEY=$(echo "$HOST_INFO" | jq -r ".$HOST_TYPE.key")
SSH_HOST=$(echo "$HOST_INFO" | jq -r ".$HOST_TYPE.name")
SSH_USER=$(echo "$HOST_INFO" | jq -r ".$HOST_TYPE.user")

echo -e "\n${C_HIL}Copying $KEY to $SSH_HOST:${C_RES}"
ssh -t -i "$KEY" "$SSH_USER@$SSH_HOST" -C "mkdir -p \"$SSH_HOME/$SSH_USER/.ssh\""
scp -i "$KEY" "$KEY" "$SSH_USER@$SSH_HOST:$SSH_HOME/$SSH_USER/.ssh/$(basename "$KEY")"
scp -i "$KEY" "$KEY.pub" "$SSH_USER@$SSH_HOST:$SSH_HOME/$SSH_USER/.ssh/$(basename "$KEY").pub"
