# Default env-setup playbook vars
#
# This YAML contains the list overridable variables in the env-setup playbooks.
# Copy this file to config.yml and any edited value will be used in place of 
# its default.
#
# USAGE EXAMPLE: replace the default dotfiles with your own.
# cp default.config.yml config.yml
# awk '{sub(/dotfiles_repo:.*/,"dotfiles_repo:\"https://github.com/my_github_screenname/dotfiles.git\""); print}' config.yml
# env-setup
---
downloads: ~/.ansible-downloads/

# name: env-setup.01-config ####################################################

# Find dotfiles via $(find . -type f | grep -vE '\.\/\.git\/' | sed -e 's/\.\///g')

# name: geerlingguy.dotfiles
# https://github.com/geerlingguy/ansible-role-dotfiles
pub_dotfiles_repo: git@github.com:Luciditi/env-setup-dotfiles.git
pub_dotfiles_repo_accept_hostkey: yes
pub_dotfiles_repo_local_destination: ~/env-setup-dotfiles
pub_dotfiles_repo_version: main
pub_dotfiles_files:
  - .bash_profile
  - .direnvrc
  - .gitconfig
  - .gitignore_global
  - .git_template
  - .inputrc
  - .macos
  - .notags
  - .p10k.zsh
  - .shell
  - .vim/colors/solarized.vim
  - .vimrc
  - .vundle.vimrc
  - .zshrc
# any file dir that needs to exist before dotfiles mapping
# useful when you don't want to keep an entire dir mapped to git
pub_dotfiles_subdirs: 
  - ~/.vim/colors/

# OPTIONAL FOR NON PUBLIC DOTFILES
# Find dotfiles via $(find . -type f | grep -vE '\.\/\.git\/' | sed -e 's/\.\///g')

# name: geerlingguy.dotfiles
# https://github.com/geerlingguy/ansible-role-dotfiles
prv_dotfiles_repo: git@github.com:Luciditi/env-setup-dotfiles.git
prv_dotfiles_repo_accept_hostkey: yes
prv_dotfiles_repo_local_destination: ~/env-setup-prv-dotfiles
prv_dotfiles_repo_version: main
prv_dotfiles_files: []
# any file dir that needs to exist before dotfiles mapping
# useful when you don't want to keep an entire dir mapped to git
prv_dotfiles_subdirs: []

# name: env-setup.02-cli #######################################################

# any homebrew taps needed for package(formulae)/cask defined below
# NOTE: in linux we'll use the the community.general.homebrew* modules
# name: geerlingguy.mac.homebrew
# https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
homebrew_taps:
  - riboseinc/easy-rsa

# NOTE: in linux we'll use the the community.general.homebrew* modules
# name: geerlingguy.mac.homebrew
envsetup_homebrew_installed_packages:
  - antigen
  - ansible
  - awscli
  - aws-shell
  - bat
  - composer
  - direnv
  - duti
  - fzf
  - gh
  - go
  - gitleaks
  - jq
  - libpq
  - sijanc147/formulas/macprefs
  - mysql-client
  - neovim
  - node
  - nvm
  - python
  - pipx
  - redis
  - rbenv
  - rg
  - ruby
  - rust
  - sops
  - tmate
  - vim
  - zsh

# name: env-setup.03-apps ######################################################

# name: geerlingguy.mac.homebrew
# https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
envsetup_homebrew_cask_apps:
  - chrome-devtools
  - chromedriver
  - docker
  - google-chrome
  - google-drive
  - font-meslo-lg-nerd-font
  - iterm2
  - postico
  - sequel-ace
  - tunnelblick
  - visual-studio-code
  - zoom

# name: geerlingguy.mac.mas
# https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/mas
mas_installed_apps:
  - { id: 803453959, name: "Slack" }
  #- { id: 497799835, name: "Xcode" }

mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }

# NOTE: will need to sign to App Store
mas_email: ""
mas_password: ""

# name: geerlingguy.mac.dock
# https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/dock
configure_dock: false

dockitems_persist:
  - name: "Docker"
    path: "/Applications/Docker.app"
    pos: 1
  - name: "Google Chrome"
    path: "/Applications/Google\ Chrome.app"
    pos: 2
  - name: "iTerm2"
    path: "/Applications/iTerm.app/"
    pos: 3
  - name: "VS Code"
    path: "/Applications/Visual\ Studio\ Code.app"
    pos: 4
  - name: "Postico 2"
    path: "/Applications/Postico 2.app"
    pos: 5
  - name: "Sequel Ace"
    path: "/Applications/Sequel Ace.app"
    pos: 6
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 7
  - name: "Tunnelblick"
    path: "/Applications/Tunnelblick.app"
    pos: 8
  - name: "Zoom"
    path: "/Applications/zoom.us.app"
    pos: 9

dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Podcasts
  - News
  - System Settings

# defaults.yml
# set any install app setting that should be defaulted
envsetup_apps_macos_settings:
  - {description: "iTerm2: Load custom settings from a folder/URL", domain: "com.googlecode.iterm2", key: "LoadPrefsFromCustomFolder", type: "bool", value: true}
  - {description: "iTerm2: Set the custom settings folder/URL", domain: "com.googlecode.iterm2", key: "PrefsCustomFolder", type: "string", value: "\"/Users/{{ ansible_user_id }}/env-setup-prv-dotfiles/.iterm2\""}
envsetup_apps_macos_sudo_settings: []

# open.yml
# manually open apps to confirm settings or manually adjust
envsetup_apps_macos_app_open:
  - "Google Chrome"
  - "iTerm"

# name: env-setup.04-packages ##################################################

# cargo packages to install
cargo_packages:
  - name: bore-cli

# composer plugins to install 
composer_plugins: 
  - name: composer/installers
  - name: dealerdirect/phpcodesniffer-composer-installer

# php packages to install
composer_packages:
  - name: phpunit/phpunit
  - name: phploc/phploc
  - name: psy/psysh
  - name: squizlabs/php_codesniffer

# go packages to install
go_packages:
  - name: github.com/ericchiang/pup@latest
  - name: github.com/ericchiang/xpup@latest

# ruby packages to install
gem_packages:
  - name: ghi

# node packages to install
npm_packages:
  - name: commitizen
  - name: eslint
  - name: npmdoctor
  - name: regexgen
  - name: saucectl
  - name: standard
  - name: typescript
  - name: yarn
  - name: '@storybook/cli'
  - name: '@vue/cli'

# python packages to install
pip_packages:
  - name: mycli
  - name: percol
  - name: virtualenv
  - name: yq

# name: env-setup.05-repos #####################################################

# a project dir where git repos will be actively worked on
git_repo_project_dir: ~/env-setup-git-repos
git_repo_projects:
  - name: env-setup
    url: git@github.com:ShawnConn/env-setup.git
    upstream: git@github.com:Luciditi/env-setup.git
    symlink: ~/Documents/Luciditi/projects/devops/env-setup

# a vendor dir where git repos will be referenced 
git_repo_vendors_dir: ~/env-setup-vendors
git_repo_vendors:
  - name: luciditi
    host: git@github.com
    projects:
      - name: env-setup-dotfiles
        depth: 1

# name: env-setup.06-os ########################################################

# system.yml
# the name of the host machine
envsetup_os_hostname: ENV-SETUP-MOST

# user.yml
# URL for the admin user
envsetup_os_avatar_url: "https://avatars.githubusercontent.com/u/1087111"

# macos.yml
# macos script (see https://mths.be/macos)
envsetup_os_macos_config_script: "{{ pub_dotfiles_repo_local_destination }}/.macos"

# set any os setting that should be defaulted
envsetup_os_macos_settings: 
  - {description: "Play feedback when volume is changed", domain: "NSGlobalDomain", key: "com.apple.sound.beep.feedback", type: "int", value: 1}
envsetup_os_macos_sudo_settings:
  - {description: "Set login message", domain: "/Library/Preferences/com.apple.loginwindow", key: "LoginwindowText", type: "string", value: "\"\""}

# set any os setting that should be defaulted
envsetup_os_linux_settings: []

# name: env-setup.07-cloud #####################################################

# main.yml
# The cloud app that should be run to start syncing
envsetup_cloud_app: "/Applications/Google Drive.app"

# The dir where cloud files reside
envsetup_cloud_dir: "/Users/{{ ansible_user_id }}/Google Drive"

# The dir where os setting should be stored
envsetup_cloud_backup_dir: "env-setup/Config/{{ ansible_hostname }}/MacPrefs"

# The script to do the os setting backup
envsetup_cloud_sync_script: "export MACPREFS_BACKUP_DIR=$CLOUD_SYNC_DIR && macprefs backup"

# dirs.yml
# The place for cloud file documents on the cloud file dir (and its hierarchy)
envsetup_cloud_project_root: "env-setup/Projects"
envsetup_cloud_project_list: 
 - MyProject
envsetup_cloud_project_dirs:
  - config
  - devops
  - keys
  - mock-data
  - notes
  - patches
  - script

# Where on the local filesystem to symlink to the cloud project dir
envsetup_cloud_project_symlink: "/Users/{{ ansible_user_id }}/Documents"

# name: env-setup.08-prefs #####################################################

# dock.yml
# Dock extras (right side) items that should persist (see geerlingguy.mac.dock)
envsetup_prefs_macos_other_dockitems_persist:
  - name: Applications
    path: "/Applications"
    view: list
    display: stack
    pos: 1
  - name: Home
    path: "/Users/{{ ansible_user_id }}"
    view: auto
    display: stack
    pos: 2
  - name: Downloads
    path: "/Users/{{ ansible_user_id }}/Downloads"
    view: auto
    display: stack
    pos: 3
  - name: Google Drive
    path: "/Users/{{ ansible_user_id }}/Google Drive"
    view: auto
    display: stack
    pos: 4

# Dock extras (right side) items that should remove (see geerlingguy.mac.dock)
envsetup_prefs_macos_other_dockitems_remove: []

# duti.yml
# Default handlers for file extensions
envsetup_prefs_macos_file_extension_handlers:
  - { extension: avi, handler: com.microsoft.VSCode }
  - { extension: c, handler: com.microsoft.VSCode }
  - { extension: cpp, handler: com.microsoft.VSCode }
  - { extension: cs, handler: com.microsoft.VSCode }
  - { extension: css, handler: com.microsoft.VSCode }
  - { extension: go, handler: com.microsoft.VSCode }
  - { extension: java, handler: com.microsoft.VSCode }
  - { extension: js, handler: com.microsoft.VSCode }
  - { extension: sass, handler: com.microsoft.VSCode }
  - { extension: scss, handler: com.microsoft.VSCode }
  - { extension: less, handler: com.microsoft.VSCode }
  - { extension: vue, handler: com.microsoft.VSCode }
  - { extension: cfg, handler: com.microsoft.VSCode }
  - { extension: json, handler: com.microsoft.VSCode }
  - { extension: jsx, handler: com.microsoft.VSCode }
  - { extension: lua, handler: com.microsoft.VSCode }
  - { extension: md, handler: com.microsoft.VSCode }
  - { extension: php, handler: com.microsoft.VSCode }
  - { extension: pl, handler: com.microsoft.VSCode }
  - { extension: py, handler: com.microsoft.VSCode }
  - { extension: rb, handler: com.microsoft.VSCode }
  - { extension: rs, handler: com.microsoft.VSCode }
  - { extension: sh, handler: com.microsoft.VSCode }
  - { extension: swift, handler: com.microsoft.VSCode }
  - { extension: txt, handler: com.microsoft.VSCode }
  - { extension: conf, handler: com.microsoft.VSCode }

# login.yml
# Default apps that start on login
envsetup_prefs_macos_login_items:
  - {name: "Google Chrome", hidden: false}
  - {name: "Google Drive", hidden: false}
  - {name: "iTerm", hidden: false}
  - {name: "Tunnelblick", hidden: false}

# defaults.yml
# set any app setting that should be defaulted
envsetup_prefs_macos_settings: []
envsetup_prefs_macos_sudo_settings: []

# open.yml
# manually open apps to confirm settings or manually adjust
envsetup_prefs_macos_app_open:
  - "Tunnelblick"

# name: gantsign.visual-studio-code-extensions
# https://github.com/gantsign/ansible-role-visual-studio-code-extensions
envsetup_prefs_visual_studio_code_extensions:
  - github.copilot
  - hashicorp.terraform
  - mhutchie.git-graph
  - ms-python.python
  - ms-azuretools.vscode-docker
  - redhat.ansible
  - streetsidesoftware.code-spell-checker
  - vscodevim.vim
  - wholroyd.jinja
  - zainchen.json
envsetup_prefs_visual_studio_code_extensions_absent: []

