#!/usr/bin/env bash

# Set stop on error / enable debug
set -euo pipefail
#set -vx

############################################################################
# MACOS INSTALL ANSIBLE
############################################################################

SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPTS_DIR/../_common"

############################################################################
# MAIN
############################################################################

echo -e "${C_HIL}Installing Ansible...${C_RES}"

SUGGEST_PIP=$(if [[ -x "$(command -v pip3)" ]]; then \
    echo "0"; else echo "${ENVSETUP_SUGGEST_PIP:-1}"; fi)

if [[ $SUGGEST_PIP == "1" ]]; then
    curl https://bootstrap.pypa.io/get-pip.py | python3
fi
sudo pip3 install ansible
