#!/usr/bin/env bash

# Set stop on error / enable debug
set -euo pipefail
#set -vx

SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPTS_DIR/../../scripts/_common"

############################################################################
# CREATE TART VMS
############################################################################
if [[ ! -x "$(command -v tart)" ]]; then
    echo -e "\n${C_ERR}tart is required!${C_RES}"
    echo -e "\nrun ${C_WARN}brew install cirruslabs/cli/tart${C_RES}"
    exit 1
fi

echo -e "\n${C_HIL}Create macos VM:${C_RES}"
tart clone "$TART_MACOS_IMAGE" "$TART_MACOS_NAME"
tart set "$TART_MACOS_NAME" --disk-size 60

echo -e "\n${C_HIL}Create linux VM:${C_RES}"
tart clone "$TART_LINUX_IMAGE" "$TART_LINUX_NAME"
tart set "$TART_LINUX_NAME" --disk-size 50

echo -e "\nrun ${C_WAR}./vm/scripts/start ($TART_MACOS_NAME|$TART_LINUX_NAME)${C_RES} to start VM"
