#!/usr/bin/env bash

# Set stop on error / enable debug
set -euo pipefail
#set -vx

SCRIPTS_DIR="$(dirname "$0")"
# shellcheck source=/dev/null
source "$SCRIPTS_DIR/../../scripts/_common"

############################################################################
# SCP TO HOST
############################################################################
SRC_FILE=${1:-""}
DST_PATH=${2:-""}

if [[ -z "$SRC_FILE" || ! -e "$SRC_FILE" || -z "$DST_PATH" ]]; then
    echo -e "usage: <SRC_FILE> <DST_PATH>"
    exit 1
fi

if [[ ! -x "$(command -v tart)" ]]; then
    echo -e "\n${C_ERR}tart is required!${C_RES}"
    echo -e "\nrun ${C_WARN}brew install cirruslabs/cli/tart${C_RES}"
    exit 1
fi

if [[ ! -x "$(command -v sshpass)" ]]; then
    echo -e "\n${C_ERR}sshpass is required!${C_RES}"
    echo -e "\nrun ${C_WARN}brew install cirruslabs/cli/sshpass${C_RES}"
    exit 1
fi

HOST_INFO=$(tart list | grep --color=none running | tr -s ' ' | cut -d' ' -f2)
SSH_HOST=$(tart ip "$HOST_INFO")
SSH_USER="admin"

echo -e "\n${C_HIL}Copying $SRC_FILE to $SSH_HOST:$DST_PATH${C_RES}"
sshpass -p admin scp -r "$SRC_FILE" "$SSH_USER"@"$SSH_HOST":"$DST_PATH"
